---
- name: DBserver setup
  hosts:  dbservers
  become: yes 
  tasks:
  - name: Install maria-db
    ansible.bultin.yum:
      name: mariadb-server
      state:  present
  - name: Install pymysql
    ansible.builtin.yum:
      name: python3-PyMySQL
      state:  present
  - name: Start mariadb service
    ansible.builtin.service:
      name: mariadb
      enabled:  yes
  - name: Create  a new database with name 'accounts'
    mysql_db:
      name: accounts
      state:  present
      login_unix_socket: /var/lib/mysql/mysql.socket